### ISSUE TITLE
**kwargs only arguments throw DOC106 and DOC109

### ISSUE THREAD

**Issue by OliverKleinBST** [jsh9/pydoclint#107]
I get 
    40: DOC106: Function `cleanse`: The option `--arg-type-hints-in-signature` is `True` but there are no argument type hints in the signature
    40: DOC109: Function `cleanse`: The option `--arg-type-hints-in-docstring` is `True` but there are no type hints in the docstring arg list

for
```

def cleanse(**kwargs) -> int:  # noqa: DOC106,  DOC109
    """Execute a cleansing process.

    Args:
        **kwargs: keyword arguments

    Returns:
        int: returns 0 if no exception
    """
```

I did not find any working syntax, nor are the noqa rules respected.

**Comment by ddelange** [comment]
Try the following toml for google docstrings ref https://github.com/jsh9/pydoclint/discussions/88#discussioncomment-7312021:
```toml
[tool.pydoclint]
style = "google"
arg-type-hints-in-docstring = false
check-return-types = false
check-yield-types = false
```

And use `**kwargs: Any`.

Or from mypy [docs](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html):
```py
# This says each positional arg and each keyword arg is a "str"
def call(self, *args: str, **kwargs: str) -> str:
    reveal_type(args)  # Revealed type is "tuple[str, ...]"
    reveal_type(kwargs)  # Revealed type is "dict[str, str]"
    request = make_request(*args, **kwargs)
    return self.do_api_query(request)
```

For the more fancy/proper approach, see https://stackoverflow.com/a/63550734/5511061.

**Comment by jsh9** [comment]
Hi, this is because `kwargs` and `args` require type hints too.

For example, this would work:

```python
from typing import Any

def cleanse(**kwargs: Any) -> int:  # noqa: DOC106,  DOC109
    """Execute a cleansing process.

    Args:
        **kwargs: keyword arguments

    Returns:
        int: returns 0 if no exception
    """
    pass

```

with this command:

```bash
pydoclint --style=google --arg-type-hunts-in-docstring=False example.py
```
