### ISSUE TITLE
Option to only check for non-existent params in pydocs, rather than params missing in pydocs

### ISSUE THREAD

**Issue by JessieSteckling** [jsh9/pydoclint#114]
I am hoping for a config option along the lines of `--require-doc-for-all-args` (where the default/current behavior is true). I would like the option to allow a pydoc that only documents some of the params. This would give more flexibility to the developer.

If possible, it would also be great if there was an option to not require return docs. Maybe `--require-return-section`

Thanks!

**Comment by jsh9** [comment]
Hi @JessieSteckling , I'd be very hesitant to add any config options that don't promote good coding style.  IMHO, only documenting certain params is not a good coding style.  In fact, part of the reason why people want to use pydoclint or darglint is to ensure all input args and return args are documented.

If you really want to achieve that, I think using `noqa` to bypass specific violations is the way to go.

**Comment by jsh9** [comment]
Closing this issue.
