### ISSUE TITLE
Program description in help is "Yes"

### ISSUE THREAD

**Issue by m472** [jsh9/pydoclint#12]
When calling pydoclint with the `--help` option the program description is "Yes". There is a comment in the source code about clicker setting it to the docstring.

Output: (truncated because only the first few lines are important)
```
Usage: pydoclint [OPTIONS] [PATHS]...

  Yes

Options:
  -s, --src TEXT                  The source code to check
  -q, --quiet                     If True, do not print the file names being
```

This happens for me both when I install `pydoclint` from source and when using `pip install .` cloned from github.

**Comment by jsh9** [comment]
😂 thanks for catching this.  This must be a placeholder that I forgot to clean up.

Let me fix this.

**Comment by jsh9** [comment]
Fixed in this commit: https://github.com/jsh9/pydoclint/commit/cc57ff5b08f2046d5b7d738809d2559deadff01c
