### ISSUE TITLE
pydoclint 0.5.2 fails to find violation in a particular folder

### ISSUE THREAD

**Issue by jsh9** [jsh9/pydoclint#139]
But pydoclint 0.4.2 was able to find a lot of violations in that folder.

This issue was originally reported by @Gabriel-p in this comment: https://github.com/jsh9/pydoclint/issues/122#issuecomment-2187265736

Created a dedicated issue here to better track this.

**Comment by jsh9** [comment]
Hi @Gabriel-p ,

After my investigation, I've found that this is actually the intended behavior.  The old behavior (which you would get with pydoclint ≤ 0.4.2) was actually the result of a bug.

In `asteca/modules/`, the docstrings are either written without any arg/return/yield/... lists (in which case pydoclint will ignore them (if `--skip-checking-short-docstrings` is set to True), or written in the numpy style, such as: https://github.com/asteca/ASteCA/blob/09204a91ed785a00ae498a20905cbfd59ab84a03/asteca/modules/nmembers.py#L231-L243

In older pydoclint versions (≤ 0.4.2), if users specify `style=sphinx`, pydoclint's docstring parser would parse the docstring several times, each with a potential style (google, numpy, sphinx, ...).  Whichever style that results in the most parsed contents gets "picked".  In particular, the docstring example above was parsed as a numpy style dosctring.

But in the new version (≥ 0.5.2), if you specify `style=sphinx`, pydoclint won't try to parse that docstring into other style.  Instead, it attempted the specified style ("sphinx"), and as a result, the arg lists written in other styles don't register at all.

**Comment by Gabriel-p** [comment]
I see. Is there any way to emulate the old behaviour in the new version? It was very useful for knowing which functions were missing a valid (sphinx) docstring

**Comment by jsh9** [comment]
Maybe there is a way: I can add a new "style" called "**_XXX_**", in which I'll use an "open docstring parser" (which means the parser will try to parse the docstring with all possible styles, and will detect which style makes the most sense).

But this will obviously slow down pydoclint's speed (because more time will be spent on parsing), so I'd suggest only using this "style" in certain use cases.

I think I need help figuring out how to name this "**_XXX_**".  Can you offer some suggestions?

**Comment by Gabriel-p** [comment]
Well, "openparser" seems descriptive enough but I think there's a perhaps simpler solution. Whatever style the user sets, if pydoclint can not parse the docstring raise a warning and that's it. That's enough to alert the user that something is not working as expected and there would be no need to add a new parser. Right now the default behaviour is apparently to fail silently.

**Comment by jsh9** [comment]
I'm closing this issue because there's a duplicated issue on the same topic: https://github.com/jsh9/pydoclint/issues/169

Hi @Gabriel-p , if you read the issue that I'm linking and if you run the sample script in my reply, you'll see that the docstring parser of pydoclint can always parse out _something_ from a string, even if the style is not expected.
