### ISSUE TITLE
Possible bug? DOC105 for arguments with default values?

### ISSUE THREAD

**Issue by mazer-ai** [jsh9/pydoclint#179]
I'm trying to specify default argument values in numpy-style docstrings and getting DOC105 errors. For example:
```python
def bar(x: bool = True) -> None:
    """
    Make a bar.

    Parameters
    ----------
    x: bool, default True
        Value of the bar
    """
    pass
```
generates a DOC105 error even though it appears to be right out of the numpy style guide about default values:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/3a1fc8c0-e16e-4654-8f87-239afc39fa14">

Before I start diving into the code, I was wondering if this is an intentional decision or if I'm misunderstanding the style guide for how to specify defaults in docstrings.

**Comment by jsh9** [comment]
Yes, this is intentional.

Please see more explanations here: https://jsh9.github.io/pydoclint/notes_for_users.html#3-notes-on-writing-type-hints

**Comment by mazer-ai** [comment]
@jsh9 Thanks for the quick response. That answers the question :-)

Could I suggest adding something very explicit about this in that file? Something simple along the lines of:

```
# 8. Default parameter values
Another consequence of using static syntax analysis is that _pydoclint_ does not support
specifying default values for function parameters in the docstring, even if they are
nominally compliant with the numpy style guide.
```

I assume this is because you can't really compare the two w/o doing evaluation. That makes perfect sense in hindsight. It is confusing as a new user when an example right out of the numpy style guide fails. Took me a while to convince myself I wasn't doing something stupid. Being explicit here might avoid another ticket from someone in the future :-)

**Comment by jsh9** [comment]
Hi @mazer-ai , in this commit (https://github.com/jsh9/pydoclint/commit/64ef92306050cd21e51a99b1dccd87a41274f6e5), I added a short explanation to README (which is also the home page of _pydoclint_'s documentation site). Thanks for the suggestion!

**Comment by mazer-ai** [comment]
@jsh9 No problem. Just to follow up -- I understand why defaults are not validated, but is there any reason not to just ignore default values if they are provided in the docstring?

I was looking through the code in `docstring_parser/numpydoc.py` that extracts type hints and looks like the regex basically grabs everything after the colon as a typehint. It's pretty straight forward to have it exclude the portion after the typehint, which would let you include a default value in the docstring, but pydoclint would just ignore it.  Can be done by modifying the regex or in pydoclint code by trimming the type string after it's extracted by the library.

I think this would make pydoclint more usable on existing code bases that are following the numpy style guide. Certainly for the code base I'm working on.

I'm happy to code this up and submit a PR if you're open to it.

**Comment by jsh9** [comment]
Yes, I'm open to a code change if it leads to one unambiguous way to document defaults in the numpy style.  I know the numpy style guide allows several ways to document defaults, but that style guide was not written with a linter in mind.

(Btw, we'd also need to consider the other two styles.)

If you have time to open a PR, we can discuss more in the PR.
