### ISSUE TITLE
InternalError: astAssign.targets[0] is of type <class 'ast.Attribute'>

### ISSUE THREAD

**Issue by niallcm** [jsh9/pydoclint#180]
Using pydoclint v0.5.9

`pydoclint.utils.internal_error.InternalError: astAssign.targets[0] is of type <class 'ast.Attribute'>`

The relevant code was adding an attribute to a method of a django ModelAdmin class:
<img width="486" alt="image" src="https://github.com/user-attachments/assets/3dac5936-0c1c-4af9-ae5e-3dac964c1688">

Related to #151

**Comment by jsh9** [comment]
I should have time to take a look this week.

**Comment by jsh9** [comment]
Could you provide a reproducible example?  Because I could not reproduce this issue with this file (`something.py`) with the following content:

```python
class MyClass:
    def large_drawing(self, obj):
        return self.drawing(obj, size=500, center=False)

large_drawing.short_description = 'Drawing'
```

Thanks!
