### ISSUE TITLE
🐛 False positive 'Return annotation not ending with `]`' on union retun type

### ISSUE THREAD

**Issue by s-weigand** [jsh9/pydoclint#44]
For union return types that start with `tuple[` (e.g. my use case `tuple[Figure, Axis] | None`) `InternalError` is raised false positively.
This is because `_isTuple` returns `True` for union types

https://github.com/jsh9/pydoclint/blob/062bb451c3b22cd8ce460417d88f1690c9710037/pydoclint/utils/return_anno.py#L59-L63

And consecutive checks are meant to work with pure tuples.

**Comment by jsh9** [comment]
Hi @s-weigand , thank you for finding out this edge case!  I'm still using the old-school `Union[..., ...]` so I didn't think of this edge case.

I've submitted a PR to fix this bug.  Would you mind taking a look and see whether I've missed any other edge cases?

Thanks again!
