### ISSUE TITLE
Cant set sphinx style in flake8 config

### ISSUE THREAD

**Issue by jonyscathe** [jsh9/pydoclint#49]
I believe that this line should allow "sphinx"?

https://github.com/jsh9/pydoclint/blob/main/pydoclint/flake8_entry.py#L144

**Comment by jsh9** [comment]
Thanks for submitting this issue!  Unit tests didn't catch it.  I believe only integration tests will catch this kind of issue.  I may consider adding integration tests in the future.

**Comment by jonyscathe** [comment]
Thanks for the quick fix
