### ISSUE TITLE
Wrong link https://github.com/jsh9/pydoclint#notes-on-doc103

### ISSUE THREAD

**Issue by kit1980** [jsh9/pydoclint#61]
The link is printed in the report and mentioned here https://github.com/jsh9/pydoclint/blob/main/docs/violation_codes.md?plain=1#L30, but it leads nowhere.

**Comment by jsh9** [comment]
Hi @kit1980 , thank you for finding this issue!

It will be fixed in https://github.com/jsh9/pydoclint/pull/62.

**Comment by jsh9** [comment]
Fixed.

The new version (0.1.8) is published to PyPI.

Btw, the correct link is now here: https://jsh9.github.io/pydoclint/violation_codes.html#notes-on-doc103
