### ISSUE TITLE
Review `DOC404` / `DOC405` (Generator vs Iterator)

### ISSUE THREAD

**Issue by llucax** [jsh9/pydoclint#76]
The rule imposed by `DOC404`/`DOC405`, including the justification in [Notes on Generator vs Iterator](https://jsh9.github.io/pydoclint/notes_generator_vs_iterator.html) doesn't go in line with Python's official documentation, which [explicitly says `Iterator`](https://docs.python.org/3/library/typing.html#typing.Generator) and [`AsyncIterator`](https://docs.python.org/3/library/typing.html#typing.AsyncGenerator) can be used as return types for functions that `yield` (even more, the documentation say that also `Iterable`/`AsyncIterable` can be used).

Having this (artificial) restriction in `pydoclint` only makes users have to write more pedantic code, which is also harder to read for the casual reader (what are all the `None` in `Generator`?), when the shorter form is supported by Python and type-checkers like `mypy` and `pyright`.

![image](https://github.com/jsh9/pydoclint/assets/1031485/61035b87-7bfb-4c29-9f99-75ce3321802d)

![image](https://github.com/jsh9/pydoclint/assets/1031485/9fdf2906-920c-4470-9f01-5ae1a3e85397)

**Comment by jsh9** [comment]
Hi @llucax , you convinced me.

I implemented https://github.com/jsh9/pydoclint/pull/77 to stop enforcing people to use Generators.

And to address the corner case where a function both yields and returns stuff, I implemented https://github.com/jsh9/pydoclint/pull/78, as well as 3 other PRs from another library:
- https://github.com/jsh9/docstring_parser_fork/pull/2
- https://github.com/jsh9/docstring_parser_fork/pull/3
- https://github.com/jsh9/docstring_parser_fork/pull/4

Please try out version 0.3.0 (or above).  If you find any issues, please don't hesitate to leave other comments!

**Comment by llucax** [comment]
Thanks @jsh9, I really appreciate it! We are finally switching all our projects to pydoclint :heart:

**Comment by jsh9** [comment]
Glad to hear that!  Thank you for making all these suggestions and providing me test cases!
