### ISSUE TITLE
google: Allow omitting `Yields:` if the yield (generator/iterator) type is `None`

### ISSUE THREAD

**Issue by llucax** [jsh9/pydoclint#79]
The same as `Returns:` is optional if the return type is `None`, [according to the google style guide it is also optional for `Yields:`](https://google.github.io/styleguide/pyguide.html#doc-function-returns).

Even when this sounds odd to have, it is an useful idiom to write context managers very easily.

```py
import collections.abc
import contextlib


@contextlib.contextmanager
def f() -> collections.abc.Iterator[None]:
    """This function doesn't yield anything."""
    # Some some initialization
    yield
    # Some cleanup


with f():
    print("I'm initialized")

print("I'm cleaned up")
```

```console
$ pydoclint --style=google --check-return-types=False --check-yield-types=False --skip-checking-short-docstrings=False yieldnone.py
Skipping files that match this pattern: \.git|\.tox
yieldnone.py
yieldnone.py
    6: DOC201: Function `f` does not have a return section in docstring 
    6: DOC402: Function `f` has "yield" statements, but the docstring does not have a "Yields" section 
```

**Comment by jsh9** [comment]
Yes, you are right.  I've pushed a code change.  It will be included in v0.3.1.

**Comment by jsh9** [comment]
Published.

**Comment by jsh9** [comment]
Btw, for this fix to work, the return type would need to be `Iterator[None]` rather than `collections.abc.Iterator[None]`.

You can read this section for more relevant explanation: https://jsh9.github.io/pydoclint/notes_for_users.html#2-cases-that-pydoclint-is-not-designed-to-handle
