### ISSUE TITLE
Is dependency on flake8 needed?

### ISSUE THREAD

**Issue by magnussommarsjo** [jsh9/pydoclint#81]
Looking into this package as a replacement for `darglint` and really like it so far. 😃 

Right now I am using `ruff` for linting instead instead of separate `flake8` packages and plugins.
I see that this project depends on `flake8` package according to the `setup.cfg` file. 
But is it really needed? I was able to uninstall `flake8` from my environment via `pip uninstall ...` and could still run `pydoclint` without issues. 

Is it possible to have `flake8` as an optional dependency instead? Or am I missing something?

**Comment by jsh9** [comment]
Hi @magnussommarsjo ,

Thanks you!  Yes, you are right.  `flake8` is not needed at all to run the checks of pydoclint.  The only place where `flake8` is needed is to selectively ignore some violation codes, as explained here: https://github.com/jsh9/pydoclint#24-native-vs-flake8

I've made a PR to make `flake8` an optional dependency.  It will be included in version 0.3.2.

**Comment by jsh9** [comment]
v0.3.2 published.  Please feel free to give it a try.  Thanks!

**Comment by magnussommarsjo** [comment]
Thank you @jsh9 for a very speedy implementation. 😄 I will try it out!
