### ISSUE TITLE
Option to disable printing config

### ISSUE THREAD

**Issue by adasium** [jsh9/pydoclint#91]
`pre-commit` checks every file separately, so the config object is printed multiple times polluting stdout.
It feels like it should only be printed for debugging purposes (e.g. with `--debug` option enabled).

https://github.com/jsh9/pydoclint/blob/04bd2316324e7d4765d646e8d23a3a99a0d0e947/pydoclint/parse_config.py#L73-L77

**Comment by jsh9** [comment]
Hi @adasium , thanks for opening up this issue!

This is because pre-commit by default runs files in small batches in parallel.  Each batch prints out a stdout statement.

I fixed it by tweaking the pre-commit hook config.

**Comment by jsh9** [comment]
The fix was published as v0.3.7.
