### ISSUE TITLE
Docs request: easier to find link to https://jsh9.github.io/pydoclint/ in `README.md`

### ISSUE THREAD

**Issue by jamesbraza** [jsh9/pydoclint#97]
Can you add a badge or text link somewhere near the top of the `README.md` for docs that takes one to https://jsh9.github.io/pydoclint/?

Mainly, when I CTRL-F for "doc" in the `README.md`, there's 0 matches at the moment that lead to https://jsh9.github.io/pydoclint/.

For reference, there is explicit text around "docs" in these repos:
- https://github.com/psf/black
- https://github.com/python/mypy

**Comment by jsh9** [comment]
Done.  See this commit: https://github.com/jsh9/pydoclint/commit/7e58949c2ae60e07fb38a963a581cbe3c526fa43

Thanks for the suggestion!
