### ISSUE TITLE
Request: ability to disable certain codes explicitly via config

### ISSUE THREAD

**Issue by jamesbraza** [jsh9/pydoclint#99]
For me, I would like to be able to globally disable specific codes via a `pyproject.toml` config file.

I see there are CLI flags for this that one can find using `pydoclint --help`:
- `allow-init-docstring` I believe disables DOC301
- `skip-checking-raises` I believe disables D5XX

I am more hoping for a rules ignore list as offered by tools like `ruff` and `pylint`.  The list would explicitly list codes like D301, as opposed to one-off CLI flags that one has to look up/figure out.

The request is thus to add support for a generalized `ignore` CLI argument, where one can input a list of codes to globally disable.

**Comment by jsh9** [comment]
Hi @jamesbraza , thanks for your interest in pydoclint!

I believe you can achieve this via the flake8 mode: https://github.com/jsh9/pydoclint#22-as-a-flake8-plugin

If you create a dedicated test environment (such as in `tox`) just for pydoclint, I believe the linting time is as fast as the native pydoclint (just a little bit slower).

**Comment by jamesbraza** [comment]
Okay sounds good there. I will close this out as resolved then, thank you!
